# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=250)),
                ('nome_empresa', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_nascimento', models.CharField(max_length=250)),
                ('curso', models.CharField(max_length=250)),
                ('conclusao', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=250)),
                ('descricao_curriculo', models.CharField(max_length=250)),
                ('nome_usuario', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=250)),
            ],
        ),
    ]
